version: '3'

services:

# Functional tests

  test:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "while ! nc -z users_service 3000; do sleep 1; done && yarn run start"
    volumes:
    - .:/usr/src/app
    depends_on:
      - users_service

# Auth service

  auth_service:
    build:
      context: ../auth-service
      dockerfile: Dockerfile
    command: yarn run start
    environment:
      PORT: 3001


# Users service

  users_service:
    build:
      context: ../users-service
      dockerfile: Dockerfile
    command: /bin/sh -c "while ! nc -z users_mysql 3306; do sleep 1; done && yarn run start"
    environment:
      PORT: 3000
    depends_on:
      - auth_service
      - users_mysql

  users_mysql:
    image: mysql:5.7
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]
    environment:
      MYSQL_ROOT_PASSWORD: root-password
      MYSQL_DATABASE: database_development
